### ISSUE TITLE
实验多次之后更简化了原理，但获得了不同的结果

### ISSUE THREAD

**Issue by lcandy2** [chablino/HUNAU_CampusNetwork_CRACKED#1]
1. 在 http://10.100.0.12:9090/zportal/loginForWeb? 中登录
2. 在客户端（mentohust）中登录

即可获得不一样的限速，但是在我的寝室里，却获得了不同的结果

<table>
<tr>
 <td>
 <td><b>下载</b>速度
 <td><b>上传</b>速度
<tr>
 <td>正常使用（有线网络）
 <td>40 Mbps
 <td>40 Mbps
<tr>
 <td>使用此方法
 <td>10 Mbps
 <td>100 Mbps
</table>

确实能达到100Mbps（但是是上传╥﹏╥）

**Comment by chablino** [comment]
hh多次测都只有10Mbps吗？
我6月份还在学校时下载竟然能跑到100Mbps。

**Comment by lcandy2** [comment]
之前那次多次测确实是只有10Mbps

11月30日更新：什么都没做，使用客户端（路由器MentoHUST）连接校园网，下载应用的时候惊奇发现能跑到100Mbps，原因未知。
